import type { LanguageModelV3 } from "@ai-sdk/provider";
import { MockLanguageModelV3 } from "ai/test";

// Shared mock model for both skill runs and note generation. The two flows
// have different expected response shapes (skill wants JSON matching
// OUTPUT_SCHEMA; note-gen wants freeform markdown in `result.text`), so we
// branch on the V3 call's `responseFormat.type`. `generateText({ output:
// Output.object(...) })` sets it to `'json'`; plain `generateText` leaves it
// as `'text'` (or undefined). That's the SDK-native discriminator — no
// system-prompt string-matching, no fragility around mode-agnostic skills
// that skip the "Active mode:" header in `build-system-prompt.ts`.
const MOCK_LATENCY_MS_FAST = 500;
const MOCK_LATENCY_MS_SLOW = 3000;

const skillBlockCanned = {
  markdown:
    "## Mock skill output\n\n" +
    "This was produced by the **Mock** language model. It does not reflect " +
    "your note's content — switch to a real provider in Settings → AI " +
    "Models to see the actual skill result.\n\n" +
    "- Pipeline wiring verified end-to-end\n" +
    "- Skill prompt was rendered with injected context\n" +
    "- Output schema accepted the result\n",
};

const skillInlineCanned = {
  markdown: "[mock rewrite — switch to a real provider for actual output]",
};

const noteGenCannedMarkdown = `# Mock Summary

This note was generated by the **Mock** language model for local development and testing. It does not reflect the content of your transcript — it is canned output used to exercise the note-generation pipeline without calling a real LLM.

## Key points

- Pipeline wiring verified end-to-end
- Transcript length is surfaced in the logs
- Replace the default language model to switch back to a real provider

## Next steps

- [ ] Select a real provider in **Settings → AI Models → Language**
- [ ] Run a fresh note-generation request
- [ ] Delete this mock summary if no longer needed
`;

// Abortable sleep — generateText forwards abortSignal to doGenerate via
// `options.abortSignal`. Without listening to it, the Stop button fires
// `InFlightRegistry.cancel` and aborts the signal, but the setTimeout
// still runs to completion before the run "finishes".
function abortableSleep(
  ms: number,
  signal: AbortSignal | undefined,
): Promise<void> {
  if (signal?.aborted) {
    return Promise.reject(new DOMException("Aborted", "AbortError"));
  }
  return new Promise((resolve, reject) => {
    const timer = setTimeout(() => {
      signal?.removeEventListener("abort", onAbort);
      resolve();
    }, ms);
    const onAbort = () => {
      clearTimeout(timer);
      reject(new DOMException("Aborted", "AbortError"));
    };
    signal?.addEventListener("abort", onAbort, { once: true });
  });
}

export function createMockLanguageModel(modelId: string): LanguageModelV3 {
  const latencyMs =
    modelId === "mock-language-slow"
      ? MOCK_LATENCY_MS_SLOW
      : MOCK_LATENCY_MS_FAST;

  return new MockLanguageModelV3({
    modelId,
    doGenerate: async (options) => {
      const wantsJson = options.responseFormat?.type === "json";

      let text: string;
      if (wantsJson) {
        // Skill flow — inline-rewrite still needs a single-line replacement
        // because `markdownToInlineChildren` rejects multi-block output.
        // `Active mode: inline-rewrite` survives in the system prompt for
        // every inline run (mode-agnostic skills only skip the header for
        // non-inline modes, per build-system-prompt.ts:18-21).
        const systemText = options.prompt
          .filter((m) => m.role === "system")
          .map((m) => (typeof m.content === "string" ? m.content : ""))
          .join("\n");
        const isInline = /Active mode: inline-rewrite/.test(systemText);
        const canned = isInline ? skillInlineCanned : skillBlockCanned;
        text = JSON.stringify(canned);
      } else {
        text = noteGenCannedMarkdown;
      }

      await abortableSleep(latencyMs, options.abortSignal);
      return {
        content: [{ type: "text" as const, text }],
        finishReason: { unified: "stop" as const, raw: "stop" },
        usage: {
          inputTokens: {
            total: undefined,
            noCache: undefined,
            cacheRead: undefined,
            cacheWrite: undefined,
          },
          outputTokens: {
            total: undefined,
            text: undefined,
            reasoning: undefined,
          },
          totalTokens: undefined,
        },
        warnings: [],
      };
    },
  });
}
