import { logger } from "@/main/logger";
import type {
  NoteGenerationInput,
  NoteGenerationProvider,
  NoteGenerationResult,
} from "./types";

const MOCK_LATENCY_MS = 500;

const CANNED_MARKDOWN = `# Mock Summary

This note was generated by the **Mock** language model for local development and testing. It does not reflect the content of your transcript — it is canned output used to exercise the note-generation pipeline without calling a real LLM.

## Key points

- Pipeline wiring verified end-to-end
- Transcript length is surfaced in the logs
- Replace the default language model to switch back to a real provider

## Next steps

- [ ] Select a real provider in **Settings → AI Models → Language**
- [ ] Run a fresh note-generation request
- [ ] Delete this mock summary if no longer needed
`;

export class MockNoteGenerationProvider implements NoteGenerationProvider {
  readonly name = "mock";

  constructor(private readonly model: string) {}

  async generateMarkdown(
    input: NoteGenerationInput,
  ): Promise<NoteGenerationResult> {
    logger.pipeline.info("Generating notes with Mock provider", {
      model: this.model,
      transcriptLength: input.transcript.length,
    });

    await new Promise((resolve) => setTimeout(resolve, MOCK_LATENCY_MS));

    return { markdown: CANNED_MARKDOWN };
  }
}
