/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteRouteImport } from './routes/_app/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppTagsRouteImport } from './routes/_app/tags'
import { Route as AppNotesRouteImport } from './routes/_app/notes'
import { Route as AppHomeRouteImport } from './routes/_app/home'
import { Route as AppFoldersRouteImport } from './routes/_app/folders'
import { Route as AppEventsRouteImport } from './routes/_app/events'
import { Route as AppSettingsIndexRouteImport } from './routes/_app/settings/index'
import { Route as AppNotesIndexRouteImport } from './routes/_app/notes.index'
import { Route as AppSettingsVocabularyRouteImport } from './routes/_app/settings/vocabulary'
import { Route as AppSettingsShortcutsRouteImport } from './routes/_app/settings/shortcuts'
import { Route as AppSettingsPreferencesRouteImport } from './routes/_app/settings/preferences'
import { Route as AppSettingsDictationRouteImport } from './routes/_app/settings/dictation'
import { Route as AppSettingsAiModelsRouteImport } from './routes/_app/settings/ai-models'
import { Route as AppSettingsAdvancedRouteImport } from './routes/_app/settings/advanced'
import { Route as AppSettingsAboutRouteImport } from './routes/_app/settings/about'
import { Route as AppNotesNoteIdRouteImport } from './routes/_app/notes.$noteId'
import { Route as AppSettingsSkillsIndexRouteImport } from './routes/_app/settings/skills/index'
import { Route as AppSettingsSkillsNewRouteImport } from './routes/_app/settings/skills/new'
import { Route as AppSettingsSkillsSkillIdRouteImport } from './routes/_app/settings/skills/$skillId'

const AppRouteRoute = AppRouteRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTagsRoute = AppTagsRouteImport.update({
  id: '/tags',
  path: '/tags',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppNotesRoute = AppNotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppHomeRoute = AppHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppFoldersRoute = AppFoldersRouteImport.update({
  id: '/folders',
  path: '/folders',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppEventsRoute = AppEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSettingsIndexRoute = AppSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppNotesIndexRoute = AppNotesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppNotesRoute,
} as any)
const AppSettingsVocabularyRoute = AppSettingsVocabularyRouteImport.update({
  id: '/settings/vocabulary',
  path: '/settings/vocabulary',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSettingsShortcutsRoute = AppSettingsShortcutsRouteImport.update({
  id: '/settings/shortcuts',
  path: '/settings/shortcuts',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSettingsPreferencesRoute = AppSettingsPreferencesRouteImport.update({
  id: '/settings/preferences',
  path: '/settings/preferences',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSettingsDictationRoute = AppSettingsDictationRouteImport.update({
  id: '/settings/dictation',
  path: '/settings/dictation',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSettingsAiModelsRoute = AppSettingsAiModelsRouteImport.update({
  id: '/settings/ai-models',
  path: '/settings/ai-models',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSettingsAdvancedRoute = AppSettingsAdvancedRouteImport.update({
  id: '/settings/advanced',
  path: '/settings/advanced',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSettingsAboutRoute = AppSettingsAboutRouteImport.update({
  id: '/settings/about',
  path: '/settings/about',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppNotesNoteIdRoute = AppNotesNoteIdRouteImport.update({
  id: '/$noteId',
  path: '/$noteId',
  getParentRoute: () => AppNotesRoute,
} as any)
const AppSettingsSkillsIndexRoute = AppSettingsSkillsIndexRouteImport.update({
  id: '/settings/skills/',
  path: '/settings/skills/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSettingsSkillsNewRoute = AppSettingsSkillsNewRouteImport.update({
  id: '/settings/skills/new',
  path: '/settings/skills/new',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSettingsSkillsSkillIdRoute =
  AppSettingsSkillsSkillIdRouteImport.update({
    id: '/settings/skills/$skillId',
    path: '/settings/skills/$skillId',
    getParentRoute: () => AppRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/events': typeof AppEventsRoute
  '/folders': typeof AppFoldersRoute
  '/home': typeof AppHomeRoute
  '/notes': typeof AppNotesRouteWithChildren
  '/tags': typeof AppTagsRoute
  '/notes/$noteId': typeof AppNotesNoteIdRoute
  '/settings/about': typeof AppSettingsAboutRoute
  '/settings/advanced': typeof AppSettingsAdvancedRoute
  '/settings/ai-models': typeof AppSettingsAiModelsRoute
  '/settings/dictation': typeof AppSettingsDictationRoute
  '/settings/preferences': typeof AppSettingsPreferencesRoute
  '/settings/shortcuts': typeof AppSettingsShortcutsRoute
  '/settings/vocabulary': typeof AppSettingsVocabularyRoute
  '/notes/': typeof AppNotesIndexRoute
  '/settings': typeof AppSettingsIndexRoute
  '/settings/skills/$skillId': typeof AppSettingsSkillsSkillIdRoute
  '/settings/skills/new': typeof AppSettingsSkillsNewRoute
  '/settings/skills': typeof AppSettingsSkillsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/events': typeof AppEventsRoute
  '/folders': typeof AppFoldersRoute
  '/home': typeof AppHomeRoute
  '/tags': typeof AppTagsRoute
  '/notes/$noteId': typeof AppNotesNoteIdRoute
  '/settings/about': typeof AppSettingsAboutRoute
  '/settings/advanced': typeof AppSettingsAdvancedRoute
  '/settings/ai-models': typeof AppSettingsAiModelsRoute
  '/settings/dictation': typeof AppSettingsDictationRoute
  '/settings/preferences': typeof AppSettingsPreferencesRoute
  '/settings/shortcuts': typeof AppSettingsShortcutsRoute
  '/settings/vocabulary': typeof AppSettingsVocabularyRoute
  '/notes': typeof AppNotesIndexRoute
  '/settings': typeof AppSettingsIndexRoute
  '/settings/skills/$skillId': typeof AppSettingsSkillsSkillIdRoute
  '/settings/skills/new': typeof AppSettingsSkillsNewRoute
  '/settings/skills': typeof AppSettingsSkillsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteRouteWithChildren
  '/_app/events': typeof AppEventsRoute
  '/_app/folders': typeof AppFoldersRoute
  '/_app/home': typeof AppHomeRoute
  '/_app/notes': typeof AppNotesRouteWithChildren
  '/_app/tags': typeof AppTagsRoute
  '/_app/notes/$noteId': typeof AppNotesNoteIdRoute
  '/_app/settings/about': typeof AppSettingsAboutRoute
  '/_app/settings/advanced': typeof AppSettingsAdvancedRoute
  '/_app/settings/ai-models': typeof AppSettingsAiModelsRoute
  '/_app/settings/dictation': typeof AppSettingsDictationRoute
  '/_app/settings/preferences': typeof AppSettingsPreferencesRoute
  '/_app/settings/shortcuts': typeof AppSettingsShortcutsRoute
  '/_app/settings/vocabulary': typeof AppSettingsVocabularyRoute
  '/_app/notes/': typeof AppNotesIndexRoute
  '/_app/settings/': typeof AppSettingsIndexRoute
  '/_app/settings/skills/$skillId': typeof AppSettingsSkillsSkillIdRoute
  '/_app/settings/skills/new': typeof AppSettingsSkillsNewRoute
  '/_app/settings/skills/': typeof AppSettingsSkillsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/events'
    | '/folders'
    | '/home'
    | '/notes'
    | '/tags'
    | '/notes/$noteId'
    | '/settings/about'
    | '/settings/advanced'
    | '/settings/ai-models'
    | '/settings/dictation'
    | '/settings/preferences'
    | '/settings/shortcuts'
    | '/settings/vocabulary'
    | '/notes/'
    | '/settings'
    | '/settings/skills/$skillId'
    | '/settings/skills/new'
    | '/settings/skills'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/events'
    | '/folders'
    | '/home'
    | '/tags'
    | '/notes/$noteId'
    | '/settings/about'
    | '/settings/advanced'
    | '/settings/ai-models'
    | '/settings/dictation'
    | '/settings/preferences'
    | '/settings/shortcuts'
    | '/settings/vocabulary'
    | '/notes'
    | '/settings'
    | '/settings/skills/$skillId'
    | '/settings/skills/new'
    | '/settings/skills'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_app/events'
    | '/_app/folders'
    | '/_app/home'
    | '/_app/notes'
    | '/_app/tags'
    | '/_app/notes/$noteId'
    | '/_app/settings/about'
    | '/_app/settings/advanced'
    | '/_app/settings/ai-models'
    | '/_app/settings/dictation'
    | '/_app/settings/preferences'
    | '/_app/settings/shortcuts'
    | '/_app/settings/vocabulary'
    | '/_app/notes/'
    | '/_app/settings/'
    | '/_app/settings/skills/$skillId'
    | '/_app/settings/skills/new'
    | '/_app/settings/skills/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRouteRoute: typeof AppRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/tags': {
      id: '/_app/tags'
      path: '/tags'
      fullPath: '/tags'
      preLoaderRoute: typeof AppTagsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/notes': {
      id: '/_app/notes'
      path: '/notes'
      fullPath: '/notes'
      preLoaderRoute: typeof AppNotesRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/home': {
      id: '/_app/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AppHomeRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/folders': {
      id: '/_app/folders'
      path: '/folders'
      fullPath: '/folders'
      preLoaderRoute: typeof AppFoldersRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/events': {
      id: '/_app/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof AppEventsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/settings/': {
      id: '/_app/settings/'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/notes/': {
      id: '/_app/notes/'
      path: '/'
      fullPath: '/notes/'
      preLoaderRoute: typeof AppNotesIndexRouteImport
      parentRoute: typeof AppNotesRoute
    }
    '/_app/settings/vocabulary': {
      id: '/_app/settings/vocabulary'
      path: '/settings/vocabulary'
      fullPath: '/settings/vocabulary'
      preLoaderRoute: typeof AppSettingsVocabularyRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/settings/shortcuts': {
      id: '/_app/settings/shortcuts'
      path: '/settings/shortcuts'
      fullPath: '/settings/shortcuts'
      preLoaderRoute: typeof AppSettingsShortcutsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/settings/preferences': {
      id: '/_app/settings/preferences'
      path: '/settings/preferences'
      fullPath: '/settings/preferences'
      preLoaderRoute: typeof AppSettingsPreferencesRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/settings/dictation': {
      id: '/_app/settings/dictation'
      path: '/settings/dictation'
      fullPath: '/settings/dictation'
      preLoaderRoute: typeof AppSettingsDictationRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/settings/ai-models': {
      id: '/_app/settings/ai-models'
      path: '/settings/ai-models'
      fullPath: '/settings/ai-models'
      preLoaderRoute: typeof AppSettingsAiModelsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/settings/advanced': {
      id: '/_app/settings/advanced'
      path: '/settings/advanced'
      fullPath: '/settings/advanced'
      preLoaderRoute: typeof AppSettingsAdvancedRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/settings/about': {
      id: '/_app/settings/about'
      path: '/settings/about'
      fullPath: '/settings/about'
      preLoaderRoute: typeof AppSettingsAboutRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/notes/$noteId': {
      id: '/_app/notes/$noteId'
      path: '/$noteId'
      fullPath: '/notes/$noteId'
      preLoaderRoute: typeof AppNotesNoteIdRouteImport
      parentRoute: typeof AppNotesRoute
    }
    '/_app/settings/skills/': {
      id: '/_app/settings/skills/'
      path: '/settings/skills'
      fullPath: '/settings/skills'
      preLoaderRoute: typeof AppSettingsSkillsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/settings/skills/new': {
      id: '/_app/settings/skills/new'
      path: '/settings/skills/new'
      fullPath: '/settings/skills/new'
      preLoaderRoute: typeof AppSettingsSkillsNewRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/settings/skills/$skillId': {
      id: '/_app/settings/skills/$skillId'
      path: '/settings/skills/$skillId'
      fullPath: '/settings/skills/$skillId'
      preLoaderRoute: typeof AppSettingsSkillsSkillIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
  }
}

interface AppNotesRouteChildren {
  AppNotesNoteIdRoute: typeof AppNotesNoteIdRoute
  AppNotesIndexRoute: typeof AppNotesIndexRoute
}

const AppNotesRouteChildren: AppNotesRouteChildren = {
  AppNotesNoteIdRoute: AppNotesNoteIdRoute,
  AppNotesIndexRoute: AppNotesIndexRoute,
}

const AppNotesRouteWithChildren = AppNotesRoute._addFileChildren(
  AppNotesRouteChildren,
)

interface AppRouteRouteChildren {
  AppEventsRoute: typeof AppEventsRoute
  AppFoldersRoute: typeof AppFoldersRoute
  AppHomeRoute: typeof AppHomeRoute
  AppNotesRoute: typeof AppNotesRouteWithChildren
  AppTagsRoute: typeof AppTagsRoute
  AppSettingsAboutRoute: typeof AppSettingsAboutRoute
  AppSettingsAdvancedRoute: typeof AppSettingsAdvancedRoute
  AppSettingsAiModelsRoute: typeof AppSettingsAiModelsRoute
  AppSettingsDictationRoute: typeof AppSettingsDictationRoute
  AppSettingsPreferencesRoute: typeof AppSettingsPreferencesRoute
  AppSettingsShortcutsRoute: typeof AppSettingsShortcutsRoute
  AppSettingsVocabularyRoute: typeof AppSettingsVocabularyRoute
  AppSettingsIndexRoute: typeof AppSettingsIndexRoute
  AppSettingsSkillsSkillIdRoute: typeof AppSettingsSkillsSkillIdRoute
  AppSettingsSkillsNewRoute: typeof AppSettingsSkillsNewRoute
  AppSettingsSkillsIndexRoute: typeof AppSettingsSkillsIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppEventsRoute: AppEventsRoute,
  AppFoldersRoute: AppFoldersRoute,
  AppHomeRoute: AppHomeRoute,
  AppNotesRoute: AppNotesRouteWithChildren,
  AppTagsRoute: AppTagsRoute,
  AppSettingsAboutRoute: AppSettingsAboutRoute,
  AppSettingsAdvancedRoute: AppSettingsAdvancedRoute,
  AppSettingsAiModelsRoute: AppSettingsAiModelsRoute,
  AppSettingsDictationRoute: AppSettingsDictationRoute,
  AppSettingsPreferencesRoute: AppSettingsPreferencesRoute,
  AppSettingsShortcutsRoute: AppSettingsShortcutsRoute,
  AppSettingsVocabularyRoute: AppSettingsVocabularyRoute,
  AppSettingsIndexRoute: AppSettingsIndexRoute,
  AppSettingsSkillsSkillIdRoute: AppSettingsSkillsSkillIdRoute,
  AppSettingsSkillsNewRoute: AppSettingsSkillsNewRoute,
  AppSettingsSkillsIndexRoute: AppSettingsSkillsIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRouteRoute: AppRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
