import { api } from "@/trpc/react";
import {
  AlertDialog,
  AlertDialogAction,
  AlertDialogCancel,
  AlertDialogContent,
  AlertDialogDescription,
  AlertDialogFooter,
  AlertDialogHeader,
  AlertDialogTitle,
} from "@/components/ui/alert-dialog";
import type { Skill } from "@/db/schema";

interface Props {
  skill: Skill | null;
  onCancel: () => void;
  onDeleted: () => void;
}

export function DeleteSkillDialog({ skill, onCancel, onDeleted }: Props) {
  const utils = api.useUtils();
  const del = api.skills.delete.useMutation({
    onSuccess: async () => {
      await utils.skills.list.invalidate();
      onDeleted();
    },
  });

  return (
    <AlertDialog open={skill !== null} onOpenChange={(open) => !open && onCancel()}>
      <AlertDialogContent>
        <AlertDialogHeader>
          <AlertDialogTitle>Delete &ldquo;{skill?.name}&rdquo;?</AlertDialogTitle>
          <AlertDialogDescription>
            This removes the skill from your library. Any artifacts already
            generated by this skill remain in your notes — only the skill
            definition is deleted.
          </AlertDialogDescription>
        </AlertDialogHeader>
        <AlertDialogFooter>
          <AlertDialogCancel onClick={onCancel}>Cancel</AlertDialogCancel>
          <AlertDialogAction
            onClick={() => {
              if (skill) del.mutate({ id: skill.id });
            }}
            disabled={del.isPending}
          >
            Delete
          </AlertDialogAction>
        </AlertDialogFooter>
      </AlertDialogContent>
    </AlertDialog>
  );
}
