const GENERATED_NOTES_HEADING = "## Meeting Notes";
const GENERATED_NOTES_SUBHEADING = "_Generated by Prismical._";
const GENERATED_NOTES_SEPARATOR = "---";

const GENERATED_SECTION_PATTERN = new RegExp(
  `^${escapeForRegex(GENERATED_NOTES_HEADING)}\\s*\\n\\s*${escapeForRegex(
    GENERATED_NOTES_SUBHEADING,
  )}\\s*\\n\\n[\\s\\S]*?\\n${escapeForRegex(GENERATED_NOTES_SEPARATOR)}\\s*(?:\\n+|$)`,
);

export function upsertGeneratedNotesSection(
  existingMarkdown: string,
  generatedMarkdown: string,
): string {
  const body = generatedMarkdown.trim();
  const generatedSection = [
    GENERATED_NOTES_HEADING,
    "",
    GENERATED_NOTES_SUBHEADING,
    "",
    body,
    "",
    GENERATED_NOTES_SEPARATOR,
  ].join("\n");

  const trimmedExisting = existingMarkdown.trim();
  if (!trimmedExisting) {
    return generatedSection;
  }

  const remainingMarkdown = trimmedExisting
    .replace(GENERATED_SECTION_PATTERN, "")
    .trim();

  if (!remainingMarkdown) {
    return generatedSection;
  }

  return `${generatedSection}\n\n${remainingMarkdown}`;
}

function escapeForRegex(value: string): string {
  return value.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}
