/**
 * Embedded migrations for the operational store.
 *
 * The .sql files are generated by drizzle-kit (see ../../../../drizzle.config.ts,
 * `pnpm exec drizzle-kit generate`) and embedded into the main bundle with
 * vite `?raw` imports — the packaged app (asar) has no migrations folder on
 * disk, so drizzle's filesystem migrator cannot run there. The ledger lives in
 * `schema_meta` (one row per version); migration 0000 creates it with
 * IF NOT EXISTS because the migrator bootstraps the ledger before applying.
 */
import type Database from 'better-sqlite3';
import migration0000 from '../../../../drizzle/0000_init.sql?raw';
import migration0001 from '../../../../drizzle/0001_recovery_outbox.sql?raw';
import migration0002 from '../../../../drizzle/0002_pause_cut_points.sql?raw';
import migration0003 from '../../../../drizzle/0003_local_models.sql?raw';
import migration0004 from '../../../../drizzle/0004_recovery_engine.sql?raw';
import migration0005 from '../../../../drizzle/0005_recovery_lifecycle.sql?raw';

export interface Migration {
  readonly version: number;
  readonly name: string;
  readonly sql: string;
}

export const MIGRATIONS: ReadonlyArray<Migration> = [
  { version: 0, name: 'init', sql: migration0000 },
  { version: 1, name: 'recovery_outbox', sql: migration0001 },
  { version: 2, name: 'pause_cut_points', sql: migration0002 },
  { version: 3, name: 'local_models', sql: migration0003 },
  { version: 4, name: 'recovery_engine', sql: migration0004 },
  { version: 5, name: 'recovery_lifecycle', sql: migration0005 },
];

const STATEMENT_BREAKPOINT = '--> statement-breakpoint';

/**
 * Applies all pending migrations. Returns the versions applied in this run.
 *
 * Each migration's statements and its ledger row run inside ONE immediate
 * transaction (BEGIN IMMEDIATE, rolled back wholesale on failure), so a
 * hand-authored migration must not carry its own BEGIN/COMMIT or a
 * `PRAGMA journal_mode` (neither is allowed inside a transaction).
 */
export function applyMigrations(client: Database.Database): number[] {
  client.exec(
    'CREATE TABLE IF NOT EXISTS `schema_meta` (`version` integer PRIMARY KEY NOT NULL, `name` text NOT NULL, `applied_at` text NOT NULL)'
  );
  const applied = new Set(
    (client.prepare('SELECT version FROM schema_meta').pluck().all() as number[]).map(Number)
  );

  const ranVersions: number[] = [];
  for (const migration of MIGRATIONS) {
    if (applied.has(migration.version)) continue;
    const statements: string[] = migration.sql
      .split(STATEMENT_BREAKPOINT)
      .map(statement => statement.trim())
      .filter(statement => statement.length > 0);
    client
      .transaction(() => {
        for (const statement of statements) client.exec(statement);
        client
          .prepare('INSERT INTO schema_meta (version, name, applied_at) VALUES (?, ?, ?)')
          .run(migration.version, migration.name, new Date().toISOString());
      })
      .immediate();
    ranVersions.push(migration.version);
  }
  return ranVersions;
}
