/**
 * Embedded migrations for the product stores (local.db + cloud caches).
 *
 * The .sql files are generated by drizzle-kit (see ../../../../drizzle-product.config.ts,
 * `pnpm exec drizzle-kit generate --config drizzle-product.config.ts`) and embedded
 * into the main bundle with vite `?raw` imports — the packaged app (asar) has no
 * migrations folder on disk, so drizzle's filesystem migrator cannot run there.
 * The ledger lives in `schema_meta` (one row per version, independent of the
 * operational store's ledger); migration 0000 creates it with IF NOT EXISTS
 * because the migrator bootstraps the ledger before applying. Migration 0000
 * also carries the hand-authored note_fts FTS5 DDL + sync triggers appended
 * after the drizzle-kit output (drizzle cannot model virtual tables).
 */
import type Database from 'better-sqlite3';
import migration0000 from '../../../../drizzle-product/0000_init.sql?raw';
import migration0001 from '../../../../drizzle-product/0001_ai_lanes.sql?raw';
import migration0002 from '../../../../drizzle-product/0002_fts_porter.sql?raw';

export interface Migration {
  readonly version: number;
  readonly name: string;
  readonly sql: string;
}

export const MIGRATIONS: ReadonlyArray<Migration> = [
  { version: 0, name: 'init', sql: migration0000 },
  // Skill body/tools/enabled/tombstone + the note_title_run revision CAS columns.
  { version: 1, name: 'ai_lanes', sql: migration0001 },
  // note_fts rebuilt with the porter stemmer (hand-authored FTS5 DDL).
  { version: 2, name: 'fts_porter', sql: migration0002 },
];

const STATEMENT_BREAKPOINT = '--> statement-breakpoint';

/**
 * Applies all pending migrations. Returns the versions applied in this run.
 *
 * Each migration's statements and its ledger row run inside ONE immediate
 * transaction (BEGIN IMMEDIATE, rolled back wholesale on failure), so a
 * hand-authored migration must not carry its own BEGIN/COMMIT or a
 * `PRAGMA journal_mode` (neither is allowed inside a transaction).
 */
export function applyProductMigrations(client: Database.Database): number[] {
  client.exec(
    'CREATE TABLE IF NOT EXISTS `schema_meta` (`version` integer PRIMARY KEY NOT NULL, `name` text NOT NULL, `applied_at` text NOT NULL)'
  );
  const applied = new Set(
    (client.prepare('SELECT version FROM schema_meta').pluck().all() as number[]).map(Number)
  );

  const ranVersions: number[] = [];
  for (const migration of MIGRATIONS) {
    if (applied.has(migration.version)) continue;
    const statements: string[] = migration.sql
      .split(STATEMENT_BREAKPOINT)
      .map(statement => statement.trim())
      .filter(statement => statement.length > 0);
    client
      .transaction(() => {
        for (const statement of statements) client.exec(statement);
        client
          .prepare('INSERT INTO schema_meta (version, name, applied_at) VALUES (?, ?, ?)')
          .run(migration.version, migration.name, new Date().toISOString());
      })
      .immediate();
    ranVersions.push(migration.version);
  }
  return ranVersions;
}
